config/routes.rb
Rails.application.routes.draw do 
  
  devise_for :users
  root "albums#index"
  resources :albums
 # resources :users
  mount AlbumStore::Base => '/'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
    attr_accessor :user_id,  :image 
    validates :name, presence: true
    belongs_to :user 
    mount_uploader :image, ImageUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :albums
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :set_album, only: [:show, :edit, :udpate, :destroy]
    before_action :authenticate_user!, except: [:show, :index]
    
    def index
       @albums = Album.all
    end

    def show 
        @album = Album.find(params[:id])
    end
    
    def new 
        @album = current_user.albums.new
    end
    
    def create 
        @album = current_user.albums.new(albums_params)
     
        if @album.save
            redirect_to @album, notice: "Created Successfully"
        else
            render :new , alert: "Failed to create"
        end
    end
    
    def edit 
        @album = Album.find(params[:id])
    end

    def update
        @album = Album.find(params[:id])
         if @album.update(albums_params)
            redirect_to @album, notice: "Updated Successfully"
        else
            render :edit, alert: 'Album could not be updated'
        end
    end

    def destroy
        @album = Album.find(params[:id])
        @album.destroy

        redirect_to @album, notice:'Deleted Successfully'
    end

    
    private

    def set_album
      @album = Album.find(params[:id])
    end

    def albums_paramas
      params.require(:album).permit(:name, :description, :image )
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_form.html.erb
<%= form_with model: @album, :html => {:multipart => true} do |form| %>
   <div class = "mb-3">
      <%= form.label :name, class: "form-label" %><br>
      <%= form.text_field :name , class: "form-control"%>
   
    </div>
   
   
    <div class = "mb-3">
    <%= form.label :description, class: "form-label" %><br>
    <%= form.text_field :description , class: "form-control"%><br>
   
    </div>
   
    <p>
      <%= form.file_field :image %>
    </p>

    <div class = "mb-3">
      <%= form.submit class: "btn btn-primary" %>
    </div>

    <% end %>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render "form", album: @album %>

app/views/albums/index.html.erb
<h1>Albums</h1>



<% if user_signed_in?%>
    <%= link_to "new", new_album_path%>
<%end%>
<br></br>

<table class="table table-striped">

  <thead>
    <tr>
      <th>User</th>  
      <th>Name</th>
      <th>Description</th>
      <th>Show</th>
      <th>Delete</th>
      <th>Photos ID</th>
    </tr>
  </thead>
  <tbody>
    <% @albums.each do |album|%>
     <tr>
      <td><%= album.user.email %></td>
      <td><%= album.name %></td>
      <td><%= album.description %></td>
      <td><%= link_to "Show", album_path(album), class:"btn btn-primary"%></td>
      <td><%= button_to "Delete", album_path(album),
      method: :delete,
      data: { confirm: "Are you sure?" },class: "btn btn-danger"%></td>
      <td><%= album.id %></td>
     </tr>
    <% end%>
  </tbody>
</table>

app/views/albums/new.html.erb
<h1>New Album</h1>
<%= render partial: "form", album: @album %>

app/views/albums/show.html.erb
<h2> Welcome to The Album</h2>

<br>

<p>
 <strong>name:</strong>
 <%= @album.name %>
</p>



<p>
  <strong>description:</strong>
  <%= @album.description%>
</p>

  <%= image_tag @album.image_url.to_s %>
  
<br>


<ul>
   <li><%=link_to "Edit", edit_album_path(@album) %></li>
   <li><%= link_to "Back", albums_path %>
   </li>
</ul>
 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-warning">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Album</a>
   <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
     
    
    
    
    
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", albums_path, class:"nav-link active"%>
        </li>
      
        
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          
          <%= link_to "New Album", new_album_path, class: "nav-link"%>
        </li>
      </ul>
      <div class="d-flex">
      <% if user_signed_in?%> 
          
          <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-danger"%>
      <% else %>
         <%= link_to "Sign In", new_user_session_path, class:"btn btn-success"%>
         <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success"%>
     
    <% end %>  
       
      </div>
    </div>
  </div>
</nav>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>album</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
      <%= render partial: "layouts/navigation" %>
      <div class="container">
      
      <%= yield %>
      </div>
     
   
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcomes#index</h1>
<p>Find me in app/views/welcomes/index.html.erb</p>
 
<%= link_to "Edit Account",  edit_user_registration_path %>
<%= button_to "Logout", destroy_user_session_path,data: {turbo: "false"}, method: :delete  %>
<%= button_to "Login",  new_user_session_path %>
<%= link_to "Create Account", new_user_registration_path%>